# -*- coding: utf-8 -*-
"""Copy of Train_custom_model_with_YOLOv5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f143vY8E__EHEHTjKRDFwoOu9ILgNPqY

# **Install Requirements**
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5  # clone repo
# %cd yolov5
# %pip install -qr requirements.txt # install dependencies
# %pip install -q roboflow

import torch
import os
from IPython.display import Image, clear_output  # to display images

print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

"""## **Data lebelling and image augmentation**
https://docs.roboflow.com/annotate
"""

# set up environment
os.environ["DATASET_DIRECTORY"] = "/content/datasets"

#after following the link above, recieve python code with these fields filled in
!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="UzICs6ZSrs2jnGcwhCmL")
project = rf.workspace("thai-thun-pfjrp").project("hand-slzri")
dataset = project.version(1).download("yolov5")

"""# **Train custom model with YOLOv5**"""

!python train.py --img 416 --batch 16 --epochs 100 --data {dataset.location}/data.yaml --weights yolov5s.pt --cache

"""# **Evalutate the performance of custom model**"""

# Commented out IPython magic to ensure Python compatibility.
# Start tensorboard
# Launch after you have started training
# logs save in the folder "runs"
# %load_ext tensorboard
# %tensorboard --logdir runs

"""# **Detect objects in an image using custom model**"""

!python detect.py --weights runs/train/exp/weights/best.pt --img 640 --conf 0.5 --source {dataset.location}/test/images

"""# **Display result image**"""

import glob
from IPython.display import Image, display

for imageName in glob.glob('/content/yolov5/runs/train/exp/*.jpg'): #assuming JPG
    display(Image(filename=imageName))
    print("\n")

"""# **Download custom model**"""

#export your model's weights for future use
from google.colab import files
files.download('./runs/train/exp/weights/best.pt')

